// Code generated by goctl. DO NOT EDIT.
package types

type ExRates struct {
	Name  string  `json:"name"`
	Unit  string  `json:"unit"`
	Value float64 `json:"value"`
	Type  string  `json:"type"`
}

type ExRatesResponse struct {
	Rates map[string]ExRates `json:"rates"`
}
