// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"chainproxy/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chainproxy/ex-rates",
				Handler: ExRatesHandler(serverCtx),
			},
		},
	)
}
